/*
Scrinch is a stand-alone Swing application that helps managing your
projects based on Agile principles.
Copyright (C) 2007  Julien Piaser, Jerome Layat, Peter Fluckiger,
Christian Lebaudy, Jean-Marc Borer
Scrinch is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
Scrinch is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.scrinch.gui;

import org.scrinch.model.Member;
import org.scrinch.model.ScrinchEnvToolkit;

public class MembersMainPanel extends javax.swing.JPanel {

    private final ScrinchEnvToolkit toolkit;

    public MembersMainPanel() {
        this(new ScrinchEnvToolkit());
    }

    public MembersMainPanel(ScrinchEnvToolkit toolkit) {
        this.toolkit = toolkit;
        initComponents();
        toolkit.addListener(new ScrinchEnvToolkit.Listener() {
            public void preferencesChanged() {
            }
            public void dataLoaded() {
                resetMemberPanels();
            }

            public void dataChanged() {
            }
        });
        resetMemberPanels();
    }

    private void resetMemberPanels() {
        removeAllMembersPanel();
        updateMembersPanel();
    }

    private void removeAllMembersPanel() {
        membersPanel.removeAll();
        membersPanel.validate();
    }

    private void updateMembersPanel() {
        for (Member hr : toolkit.getMemberFactory().getMemberList()) {
            addMemberPanel(hr);
        }
    }

    private void addMemberPanel(Member hr) {
        final MemberPanel memberPanel = new MemberPanel(toolkit);
        memberPanel.setMember(hr, new MemberPanel.Listener() {
            public void removed() {
                membersPanel.remove(memberPanel);
                resetMemberPanels();
            }
            public void changed() {
                resetMemberPanels();
            }
        });
        membersPanel.add(memberPanel);
        membersPanel.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membersTopPanel = new javax.swing.JPanel();
        addMember = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        membersPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        addMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/scrinch/gui/111-user.png"))); // NOI18N
        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });
        membersTopPanel.add(addMember);

        add(membersTopPanel, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NickName");
        jPanel2.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FullName");
        jPanel2.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Internal Phone");
        jPanel2.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mobile Phone");
        jPanel2.add(jLabel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        membersPanel.setLayout(new javax.swing.BoxLayout(membersPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(membersPanel);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
    toolkit.getMemberFactory().createMember();
    resetMemberPanels();
}//GEN-LAST:event_addMemberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel membersPanel;
    private javax.swing.JPanel membersTopPanel;
    // End of variables declaration//GEN-END:variables
}
