pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('unit-testing/java-bad-coverage') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('unit-testing/java-bad-coverage') {
                    sh 'mvn verify'
                }
            }
        }

        stage('SpotBugs Analysis') {
            steps {
                dir('unit-testing/java-bad-coverage') {
                    sh 'mvn spotbugs:spotbugs'
                }
            }
        }

        stage('Package') {
            steps {
                dir('unit-testing/java-bad-coverage') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            // Publish test results
            junit '**/target/surefire-reports/*.xml'
            
            // Publish code coverage
            recordCoverage(tools: [[parser: 'JACOCO', pattern: 'unit-testing/java-bad-coverage/target/site/jacoco/jacoco.xml']])
            
            // Archive SpotBugs HTML report
            archiveArtifacts artifacts: '**/target/spotbugs.html', allowEmptyArchive: true
            
            // Archive JAR artifacts
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }

        success {
            echo 'Build succeeded!'
        }

        failure {
            echo 'Build failed!'
        }
    }
}

