pipeline {
    agent {
        docker {
            image 'python:3'
            args '-u root'
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('unit-testing/python-good-coverage') {
                    sh '''
                        pip3 install poetry==1.6.1
                        poetry config virtualenvs.in-project true
                        poetry install --no-interaction --no-ansi
                    '''
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('unit-testing/python-good-coverage') {
                    sh '''
                        poetry run pytest --verbose \
                            --cov=src/calculator \
                            --cov-report=html:htmlcov \
                            --cov-report=xml:coverage.xml \
                            --cov-report=term-missing \
                            --cov-fail-under=90 \
                            --junitxml=test-results.xml
                    '''
                }
            }
        }
        
        stage('BDD Tests') {
            steps {
                dir('unit-testing/python-good-coverage') {
                    sh 'poetry run behave --format=pretty'
                }
            }
        }
        
        stage('Pylint Analysis') {
            steps {
                dir('unit-testing/python-good-coverage') {
                    sh 'poetry run pylint src/calculator --output-format=parseable --reports=yes > pylint-report.txt || true'
                }
            }
        }
    }
    
    post {
        always {
            junit allowEmptyResults: true, testResults: 'unit-testing/python-good-coverage/test-results.xml'
            
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'unit-testing/python-good-coverage/htmlcov',
                reportFiles: 'index.html',
                reportName: 'Coverage Report'
            ])
            
            archiveArtifacts artifacts: 'unit-testing/python-good-coverage/coverage.xml,unit-testing/python-good-coverage/pylint-report.txt', allowEmptyArchive: true
        }
        
        success {
            echo 'Build succeeded!'
        }
        
        failure {
            echo 'Build failed!'
        }
    }
}
