pipeline {
    agent {
        docker {
            image 'python:3'
            args '-u root'
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh '''
                    pip3 install poetry==1.6.1
                    poetry config virtualenvs.in-project true
                    poetry install --no-interaction --no-ansi
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh '''
                    poetry run pytest --verbose \
                        --cov=src/calculator \
                        --cov-report=html:htmlcov \
                        --cov-report=xml:coverage.xml \
                        --cov-report=term-missing \
                        --cov-fail-under=90 \
                        --junitxml=test-results.xml
                '''
            }
        }
        
        stage('BDD Tests') {
            steps {
                sh 'poetry run behave --format=pretty'
            }
        }
        
        stage('Pylint Analysis') {
            steps {
                sh 'poetry run pylint src/calculator --output-format=parseable --reports=yes > pylint-report.txt || true'
            }
        }
    }
    
    post {
        always {
            junit allowEmptyResults: true, testResults: 'test-results.xml'
            
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'htmlcov',
                reportFiles: 'index.html',
                reportName: 'Coverage Report'
            ])
            
            archiveArtifacts artifacts: 'coverage.xml,pylint-report.txt', allowEmptyArchive: true
        }
        
        success {
            echo 'Build succeeded!'
        }
        
        failure {
            echo 'Build failed!'
        }
    }
}
