/*
 Scrinch is a stand-alone Swing application that helps managing your
 projects based on Agile principles.
 Copyright (C) 2007  Julien Piaser, Jerome Layat, Peter Fluekiger,
 Christian Lebaudy, Jean-Marc Borer

 Scrinch is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Scrinch is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.scrinch.gui;

import java.util.Collection;
import org.scrinch.model.ItemToolkit;
import org.scrinch.model.ScrinchEnvToolkit;
import org.scrinch.model.Target;

public class ReleaseNotesDialog extends javax.swing.JDialog {

    private final ScrinchEnvToolkit toolkit;

    public ReleaseNotesDialog(java.awt.Frame parent, Target releaseNotesTarget, ScrinchEnvToolkit toolkit) {
        super(parent, true);
        initComponents();
        this.toolkit = toolkit;
        ScrinchGuiToolkit.centerFrame(this);
        fillTextFieldAccordingTo(releaseNotesTarget);
    }

    private void fillTextFieldAccordingTo(Target releaseNotesTarget){
        Collection results = ItemToolkit.findItemsWithTarget(toolkit.getItemFactory().getItemList(), releaseNotesTarget);
        releaseNotesTextField.setText("Release "+releaseNotesTarget.getLabel()+"\n");
        for (Object modification:results) {
            releaseNotesTextField.append(modification.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        releaseNotesTextField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        releaseNotesTextField.setColumns(20);
        releaseNotesTextField.setEditable(false);
        releaseNotesTextField.setRows(5);
        jPanel2.add(releaseNotesTextField, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea releaseNotesTextField;
    // End of variables declaration//GEN-END:variables
}
